#! /usr/bin/ruby -E:UTF-8
# -*- mode:Ruby; tab-width:4; coding:UTF-8; -*-
# vi:set ft=ruby ts=4 fenc=UTF-8 :
#----------------------------------------------------------------
# フロッピーディスクイメージファイルの識別
#
# 2024/09/14 opa⁠🙂
#----------------------------------------------------------------

require "optparse"
require "pp"

ProgName = "fdimageid"
Version = "0.01"
#=====dpk===== Copyright2024
Copyright = "Copyright (c) 2024 by opa"
#=====dpk=====

class String
	def to_byte;	unpack1("C");	end
	def to_word;	unpack1("v");	end
	def to_dword;	unpack1("V");	end

	def to_bytes;	unpack("C*");	end
	def to_words;	unpack("v*");	end
	def to_dwords;	unpack("V*");	end
end

class Integer
	def to_hex;	"#{to_s(16)}h";	end
end

def read_file(filename, offset=0, length=nil)
	return IO.binread(filename, length, offset)
end

def write_file(filename, data)
	return IO.binwrite(filename, data)
end

class DiskImage
	attr_accessor(:mediatype, :track, :writeprotect, :comment)

	def initialize(filename:nil, data:nil)
		clear

		if filename
			data = read_file(filename)
		end

		if data
			load(data)
		end
	end

	def clear
		@mediatype = nil # :"1d", :"1dd", :"2d", :"2dd", :"2hd", :unknown
		@track = []
		@writeprotect = nil # true:Write Protected false:Writeable
		@comment = nil
		return self
	end

	def to_h
		return {
			mediatype: @mediatype,
			track: @track.map{ |t| t && t.to_h },
			writeprotect: @writeprotect,
			comment: @comment,
		}
	end

	class Track
		attr_accessor(:sector)

		def initialize
			clear
		end

		def clear
			@sector = []
			return self
		end

		def to_h
			return {
				sector: @sector.map{ |r| r && r.to_h },
			}
		end

		# トラックに含まれるセクタ数
		def nsectors
			return @sector.length
		end

		# 全バイトが同一値であるか
		def is_uniform?(test_value=nil)
			return nil  if @sector.empty?
			test_value ||= @sector[0].data[0]
			return @sector.all?{ |s| s.is_uniform?(test_value) }
		end
	end

	class Sector
		attr_accessor(:data, :c, :h, :r, :n, :mfm, :ddam, :cmd, :status, :st0, :st1, :st2, :pda)

		def initialize
			clear
		end

		def clear
			@data = ""
			@c = nil
			@h = nil
			@r = nil
			@n = nil
			@mfm = nil		# false:FM(S) true:MFM(D,H)
			@ddam = nil		# false:DAM true:DDAM
			@cmd = nil		# BIOS Read Data Command
			@status = nil	# BIOS Read Data Status 0:Normal Terminate
			@st0 = nil		# ST0
			@st1 = nil		# ST1
			@st2 = nil		# ST2
			@pda = nil		# PDA 0x90:1.2M 0x30:1.44M 0x10:640K
			return self
		end

		def to_h
			return {
				data: @data,
				c: @c,
				h: @h,
				r: @r,
				n: @n,
				mfm: @mfm,
				ddam: @ddam,
				cmd: @cmd,
				status: @status,
				st0: @st0,
				st1: @st1,
				st2: @st2,
				pda: @pda,
			}
		end

		# 全バイトが同一値であるか
		def is_uniform?(test_value=nil)
			return nil  if @data.empty?
			test_value ||= @data[0]
			return @data == test_value * @data.length
		end
	end

	# 空か?
	def empty?
		return @mediatype.nil? && @writeprotect.nil? && @comment.nil? && xtracks == 0
	end

	# データのある最終トラック番号
	def ntracks
		last_empty_track_count = @track.reverse.find_index { |t| !t.nil? }
		if last_empty_track_count
			return @track.length - last_empty_track_count
		else
			return 0 # データの有るトラックが無い
		end
	end

	# データのあるトラック数
	def xtracks
		return @track.count { |t| !t.nil? }
	end

	# 全データをCHRN順に連結したもの
	def whole_data
	end

	# ファイルサイズチェック(内部用)
	def excess_data_check(expect, actual)
		excess_data_length = expect - actual
		if excess_data_length > 0
			$stdout.print("  末尾に不要なデータがあります(#{excess_data_length}バイト余剰)\n")
		elsif excess_data_length < 0
			$stdout.print("  読み込み中に末尾に達しました(#{-excess_data_length}バイト不足)\n")
		end
	end
	protected(:excess_data_check)

	# 情報を表示
	def report_all
		if empty?
			$stdout.print("  データがありません(初期状態)\n")
			return
		end

		if @comment && !@comment.empty?
			$stdout.print("  コメント: #{@comment.inspect}\n")
		end

		ntracks_std = nil
		if @mediatype
			case @mediatype
			when :"1d"
				mediatype_s = "1D"
				ntracks_std = 40
			when :"1dd"
				mediatype_s = "1DD"
				ntracks_std = 80
			when :"2d"
				mediatype_s = "2D"
				ntracks_std = 40 * 2
			when :"2dd"
				mediatype_s = "2DD"
				ntracks_std = 80 * 2
			when :"2hd"
				mediatype_s = "2HD"
				ntracks_std = 80 * 2 # or 77 * 2
			when :unknown
				mediatype_s = "不明"
			else
				mediatype_s = "不正な値(#{@mediatype})"
			end
			$stdout.print("  メディア種別: #{mediatype_s}\n")
		end

		if !@writeprotect.nil?
			if @writeprotect
				$stdout.print("  書き込み禁止\n")
			else
				$stdout.print("  書き込み可\n")
			end
		end

		nsectors = {}
		sector_size = {}
		mfm_count = {}
		ddam_count = 0
		status_count = {}
		@track.each.with_index do |trk, trkno|
			next  if !trk

			nsec = trk.nsectors
			nsectors[nsec] ||= 0
			nsectors[nsec] += 1

			sector_count = []
			trk.sector.each.with_index do |s, sec|
				if s.c != trkno / 2
					$stdout.print("  トラック#{trkno+1}のセクタのC値が特殊です: #{s.c} != #{trkno / 2}\n")
				end

				if s.h != trkno % 2
					$stdout.print("  トラック#{trkno+1}のセクタのH値が特殊です: #{s.h} != #{trkno % 2}\n")
				end

				# インターリーブしてると普通に異なるのでコメントアウト
				# if s.r != sec + 1
				# 	$stdout.print("  トラック#{trkno+1}のセクタのR値が特殊です: #{s.r} != #{sec+1}\n")
				# end

				sector_count[s.r] ||= 0
				sector_count[s.r] += 1

				ssize = s.data.length
				sector_size[ssize] ||= 0
				sector_size[ssize] += 1

				if !s.mfm.nil?
					mfm_count[s.mfm] ||= 0
					mfm_count[s.mfm] += 1
				end

				if s.ddam == true
					ddam_count += 1
				end

				if !s.status.nil? && s.status != 0
					status_count[s.status] ||= 0
					status_count[s.status] += 1
				end
			end

			sector_count.each.with_index do |count, sec|
				count ||= 0
				if sec == 0
					if count > 0
						$stdout.print("  トラック#{trkno+1}にR値が#{sec}のセクタがあります\n")
					end
				else
					if count < 1
						$stdout.print("  トラック#{trkno+1}にR値が#{sec}のセクタがありません\n")
					elsif count > 1
						$stdout.print("  トラック#{trkno+1}にR値が#{sec}のセクタが複数あります\n")
					end
				end
			end
		end

		sector_size = sector_size.to_a.sort_by{ |e| e[1] }.reverse
		if !sector_size.empty?
			sector_size_s = "#{sector_size[0][0]}バイト"
			if sector_size.length >= 2
				sector_size_s += "(混在あり)"
			end
		else
			sector_size_s = "0バイト"
		end

		nsectors = nsectors.to_a.sort_by{ |e| e[1] }.reverse
		if !nsectors.empty?
			nsectors_s = "#{nsectors[0][0]}セクタ"
			if nsectors.length >= 2
				nsectors_s += "(混在あり)"
			end
		else
			nsectors_s = "0セクタ"
		end

		if @mediatype == :"2hd" && !sector_size.empty? && !nsectors.empty?
			if (sector_size[0][0] == 1024 && nsectors[0][0] == 8) ||
				(sector_size.length >= 2 && sector_size[0][0] == 256 && sector_size[1][0] == 128 && nsectors[0][0] == 26)

				ntracks_std = 77 * 2
			end
		end

		if(ntracks == xtracks)
			tracks_s = "#{ntracks}トラック"
		else
			tracks_s = "#{ntracks}(#{xtracks})トラック"
		end

		if ntracks_std
			if ntracks == ntracks_std
				tracks_s += "(標準)"
			else
				tracks_s += "(標準は#{ntracks_std})"
			end
		end

		$stdout.print("  #{sector_size_s} × #{nsectors_s} × #{tracks_s}\n")

		if mfm_count.length >= 2
			$stdout.print("  FM/MFM混在: FM:#{mfm_count[false]}セクタ MFM:#{mfm_count[true]}セクタ\n")
		end

		if ddam_count > 0
			$stdout.print("  Deleted Data Address Markの立ったセクタが#{ddam_count}個あります\n")
		end

		status_count = status_count.to_a.sort_by{ |e| e[1] }.reverse
		if !status_count.empty?
			status_count_s = "#{status_count[0][0].to_hex}が#{status_count[0][1]}個"
			status_count_s += " 他"  if status_count.length >= 2
			$stdout.print("  FDC Statusが0でないセクタがあります(#{status_count_s})\n")
		end

		uniform_map = @track.map do |t|
			if t&.is_uniform?
				t.sector[0].data[0]
			else
				false
			end
		end

		trkno = 1
		uniform_map.chunk{ |d| d }.each do |c|
			c_tracks = c[1].length

			if c[0]
				if c_tracks == 1
					$stdout.print("  トラック#{trkno}は全て#{c[0].ord.to_hex}です\n")
				else
					$stdout.print("  トラック#{trkno}～#{trkno+c_tracks-1}は全て#{c[0].ord.to_hex}です\n")
				end
			end

			trkno += c_tracks
		end
	end
end

# DIFC.X(.dim) ヘッダ(256バイト)+べたデータ https://stdkmd.net/xeij/source/FDMedia.htm https://www.pc98.org/project/doc/dim.html
class DIM < DiskImage
	HEADER_SIZE = 0x100

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[171, 15] == "DIFC HEADER  \0\0" &&
			[0x00, 0x01, 0x02, 0x03, 0x09, 0x11].include?(filedata[0].to_byte)
	end

	def load(filedata)
		clear

		# DIFC.Xバージョン
		difc_version = filedata[0xfe].to_byte
		difc_version_s = "1.%02x" % difc_version
		$stdout.print("  DIFC.xバージョン: #{difc_version_s}\n")

		# メディアタイプ
		media_byte = filedata[0].to_byte
		case media_byte
		when 0x00 # 2HD(1.23MB)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 77, 2, 8, 1024
		when 0x01 # 2HS(1.44MB)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 80, 2, 9, 1024
		when 0x02 # 2HC(1.2MB)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 80, 2, 15, 512
		when 0x03 # 2HDE(1.44MB)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 80, 2, 9, 1024
		when 0x09 # 2HQ(1.44MB)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 80, 2, 18, 512
		else
			$stdout.print("  メディアタイプ不明: #{media_byte.to_hex}\n")
			@mediatype = :unknown
			cyls, heads, nsecs, ssize = 0, 0, 0, 0
		end

		# トラック保存状態
		xtrack_map = filedata[1, 170].to_bytes
		xtrack_map.each.with_index do |flag, trkno|
			if flag == 0 || flag == 1
				# OK:NOP
			else
				$stdout.print("  #{trkno+1}トラックのデータ有無フラグが不正: #{flag}\n")
			end
		end

		# ファイル作成時刻
		create_time = filedata[0xba, 8]
		if create_time != "\0" * 8
			create_time = create_time.unpack("CH2H2H2CH2H2H2").map{ |e| e.to_i }
			create_time[0] = "日月火水木金土"[create_time[0]]
			create_time[1] = 1980 + create_time[1]
			$stdout.print("  ファイル作成時刻: " +
				"#{create_time[1]}/#{"%02d" % create_time[2]}/#{"%02d" % create_time[3]}(#{create_time[0]}) " +
				"#{create_time[5]}:#{"%02d" % create_time[6]}:#{"%02d" % create_time[7]}(#{(create_time[4]==0) ? "12" : "24"}時間計)\n")
		end

		# コメント
		@comment = filedata[0xc2, 60].force_encoding("WINDOWS-31J").encode.sub(/\0+$/, "")

		# オーバートラック
		header_ntracks = filedata[0xff].to_byte
		$stdout.print("  ヘッダのトラック数: #{header_ntracks}トラック\n")  if header_ntracks > 0

		# データ本体
		offset = HEADER_SIZE
		xtrack_map.each.with_index do |flag, trkno|
			case flag
			when 0 # なし
				@track[trkno] = nil
			when 1 # あり
				cyl = trkno / heads
				head = trkno % heads

				trk = (@track[trkno] ||= Track.new)
				(1 .. nsecs).each do |sec|
					s = Sector.new
					s.c = cyl # シリンダは0オリジン
					s.h = head # ヘッドは0オリジン
					s.r = sec # レコードは1オリジン
					s.n = (ssize / 128).bit_length - 1
					s.data = filedata[offset, ssize] || ""
					offset += ssize
					trk.sector << s
				end
			end
		end

		excess_data_check(filedata.length, offset)
	end

	def dump
		raise("Not implemented")
	end
end

# T98Next R0(.nfd) ヘッダ(68112バイト)+べたデータ https://www.pc98.org/project/doc/nfdr0.txt
class NFD_R0 < DiskImage
	HEADER_SIZE = 0x10a10

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[0, 15] == "T98FDDIMAGE.R0\0"
	end

	def load(filedata)
		clear

		@comment = filedata[0x10, 0x100].force_encoding("WINDOWS-31J").encode.sub(/\0+$/, "")
		dwHeadSize = filedata[0x10 + 0x100, 4].to_dword
		@writeprotect = (filedata[0x10 + 0x100 + 4].to_byte != 0) ? true : false
		byHead = filedata[0x10 + 0x100 + 5].to_byte

		$stdout.print("  ヘッダ部のヘッド数: #{byHead}\n")

		id_offset = 0x120
		data_offset = dwHeadSize
		(0 ... 163).each do |trkno|
			(0 ... 26).each do |sec|
				s = Sector.new
				s.c, s.h, s.r, s.n, s.mfm, s.ddam, s.status, s.st0, s.st1, s.st2, s.pda =
					filedata[id_offset, 11].unpack("C11")
				id_offset += 0x10

				next  if s.c == 0xff

				if s.c > 90 || s.h > 1 || s.r > 32 || s.n > 6
					$stdout.print("  トラック#{trkno+1}のCHRN不正: #{s.c}/#{s.h}/#{s.r}/#{s.n}\n")
					next  if s.n > 6 # 致命的なのでこのセクタはスキップ
				end

				case s.mfm
				when 0
					s.mfm = false
				when 1
					s.mfm = true
				else
					$stdout.print("  flMFMの値が不正: #{s.mfm}\n")
					s.mfm = nil
				end

				case s.ddam
				when 0
					s.ddam = false
				when 1
					s.ddam = true
				else
					$stdout.print("  flDDAMの値が不正: #{s.ddam}\n")
					s.ddam = nil
				end

				ssize = 128 << s.n
				s.data = filedata[data_offset, ssize] || ""
				data_offset += ssize

				trk = (@track[trkno] ||= Track.new)
				trk.sector << s
			end
		end

		excess_data_check(filedata.length, data_offset)
	end

	def dump
		raise("Not implemented")
	end
end

# T98Next R1(.nfd) ヘッダ(全体(960バイト)+セクタ+特殊読み込み)+データ https://www.pc98.org/project/doc/nfdr1.txt
class NFD_R1 < DiskImage
	HEADER_SIZE = 0x3c0

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[0, 15] == "T98FDDIMAGE.R1\0"
	end

	def load(filedata)
		clear

		@comment = filedata[0x10, 0x100].force_encoding("WINDOWS-31J").encode.sub(/\0+$/, "")
		dwHeadSize = filedata[0x10 + 0x100, 4].to_dword
		@writeprotect = (filedata[0x10 + 0x100 + 4].to_byte != 0) ? true : false
		byHead = filedata[0x10 + 0x100 + 5].to_byte
		dwTrackHead = filedata[0x10 + 0x100 + 0x10, 4 * 164].to_dwords
		dwAddInfo = filedata[0x10 + 0x100 + 0x10 + 4 * 164, 4].to_dword

		$stdout.print("  ヘッダ部のヘッド数: #{byHead}\n")
		$stdout.print("  追加情報ヘッダのアドレスが0以外です: #{dwAddInfo.to_hex}\n")  if dwAddInfo != 0

		data_offset = dwHeadSize
		sp_read_count = {}
		dwTrackHead.each.with_index do |track_offset, trkno|
			next  if track_offset == 0

			nsecs, wDiag = filedata[track_offset, 2 * 2].to_words
			track_offset += 0x10

			trk = (@track[trkno] ||= Track.new)
			(0 ... nsecs).each do |sec|
				s = Sector.new
				s.c, s.h, s.r, s.n, s.mfm, s.ddam, s.status, s.st0, s.st1, s.st2, byRetry, s.pda =
					filedata[track_offset, 12].unpack("C12")
				track_offset += 0x10

				if s.c > 90 || s.h > 1 || s.r > 32 || s.n > 6
					$stdout.print("  トラック#{trkno+1}のCHRN不正: #{s.c}/#{s.h}/#{s.r}/#{s.n}\n")
					next  if s.n > 6 # 致命的なのでこのセクタはスキップ
				end

				case s.mfm
				when 0
					s.mfm = false
				when 1
					s.mfm = true
				else
					$stdout.print("  flMFMの値が不正: #{s.mfm}\n")
					s.mfm = nil
				end

				case s.ddam
				when 0
					s.ddam = false
				when 1
					s.ddam = true
				else
					$stdout.print("  flDDAMの値が不正: #{s.ddam}\n")
					s.ddam = nil
				end

				ssize = 128 << s.n
				if byRetry == 0
					s.data = filedata[data_offset, ssize] || ""
					data_offset += ssize
				else
					$stdout.print("  リトライデータが存在します: 1+#{byRetry}回\n")
					s.data = []
					(0 .. byRetry).each do
						s.data << (filedata[data_offset, ssize] || "")
						data_offset += ssize
					end
				end

				trk.sector << s
			end

			(0 ... wDiag).each do
				d_cmd, d_c, d_h, d_r, d_n, d_byStatus, d_bySTS0, d_bySTS1, d_bySTS2, d_byRetry, d_dwDataLen, d_byPDA =
					filedata[track_offset, 15].unpack("C10VC")
				track_offset += 0x10
				data_offset += d_dwDataLen

				sp_read_count[d_cmd] ||= 0
				sp_read_count[d_cmd] += 1
			end
		end

		sp_read_count = sp_read_count.to_a.sort_by{ |e| e[1] }.reverse
		sp_read_count.each do |cmd, count|
			case cmd
			when 0x0
				cmd_s = "Seek"
			when 0x1
				cmd_s = "Verify"
			when 0x2
				cmd_s = "Read Diagnostic"
			when 0x3
				cmd_s = "Initialize"
			when 0x4
				cmd_s = "Sense"
			when 0x5
				cmd_s = "Write Data"
			when 0x6
				cmd_s = "Read Data"
			when 0x7
				cmd_s = "Recalibrate"
			when 0x9
				cmd_s = "Write Deleted Data"
			when 0xa
				cmd_s = "Read ID"
			when 0xc
				cmd_s = "Read Deleted Data"
			when 0xd
				cmd_s = "Format Track"
			when 0xe
				cmd_s = "Set Operation Mode"
			else
				cmd_s = "不明なコマンド"
			end

			$stdout.print("  特殊読み込みデータが存在します: #{cmd_s}: #{count}個\n")
		end

		excess_data_check(filedata.length, data_offset)
	end

	def dump
		raise("Not implemented")
	end
end

# SL9821(.slf) フォーマットヘッダ(16バイト)+トラックヘッダ(32*80*2=5120バイト)+データ https://www.satotomi.com/pifdc/pifdc_slf.html
class SLF < DiskImage
	HEADER_SIZE = 16 + 32 * 80 * 2

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[0, 4] == "FDIM" &&
			filedata[4, 4].to_dword == 0x10000 &&
			filedata[8, 4].to_dword == filedata.length
	end

	def load(filedata)
		clear

		version, filesize, flag = filedata[4, 12].to_dwords
		$stdout.print("  SLFバージョン: #{version.to_hex}\n")

		if filesize != filedata.length
			$stdout.print("  ヘッダのファイルサイズと実際のサイズが異なります: #{filesize} != #{filedata.length}\n")
		end

		if flag != 0
			$stdout.print("  フラグが設定されています: #{flag.to_hex}\n")
		end

		cyls, heads = 80, 2
		(0 ... cyls * heads).each do |trkno|
			tdata_offset, tdata_size, unformat_size, data_type, nsecs, gap4a_size, sync_size, gap1_size =
				filedata[0x10 + 0x20 * trkno, 28].unpack("V3v2V3")

			case data_type
			when 0xffff # -1:未フォーマット
				@track[trkno] = nil
			when 0 # 物理フォーマットデータ
				$stdout.print("  物理フォーマットのトラックには対応していません: #{trkno+1}トラック\n")
				@track[trkno] = nil
			when 1, 2 # 1:FM/2:MFMフォーマットデータ
				sheader_offset = tdata_offset
				trk = (@track[trkno] ||= Track.new)
				(1 .. nsecs).each do |sec|
					s = Sector.new
					sdata_offset, status, isync_size, gap2_size, dsync_size, gap3_size,
						id_crc, data_crc, idam_pattern, s.c, s.h, s.r, s.n, dataam_pattern =
						filedata[sheader_offset, 32].unpack("V2v6VC4V")
					sheader_offset += 0x20

					if s.c > 90 || s.h > 1 || s.r > 32 || s.n > 6
						$stdout.print("  トラック#{trkno+1}のCHRN不正: #{s.c} #{s.h} #{s.r} #{s.n}\n")
						next  if s.n > 6 # 致命的なのでこのセクタはスキップ
					end

					sdata_offset = tdata_offset + sdata_offset
					ssize = 128 << s.n
					s.mfm = (data_type == 2) ? true : false
					s.data = filedata[sdata_offset, ssize] || ""
					trk.sector << s

					if (status & 0x1) != 0
						$stdout.print("  ステータス(#{id_c}/#{id_h}/#{id_s}/#{id_n}): IDAMパターンエラー\n")
					end
					if (status & 0x2) != 0
						$stdout.print("  ステータス(#{id_c}/#{id_h}/#{id_s}/#{id_n}): ID CRCエラー\n")
					end
					if (status & 0x4) != 0
						$stdout.print("  ステータス(#{id_c}/#{id_h}/#{id_s}/#{id_n}): DATAAMパターンエラー\n")
					end
					if (status & 0x8) != 0
						$stdout.print("  ステータス(#{id_c}/#{id_h}/#{id_s}/#{id_n}): DATA CRCエラー\n")
					end
					if (status & 0x10) != 0
						$stdout.print("  ステータス(#{id_c}/#{id_h}/#{id_s}/#{id_n}): セクタ構造のエラー\n")
					end
					if (status & 0x100) != 0
						$stdout.print("  ステータス(#{id_c}/#{id_h}/#{id_s}/#{id_n}): Deletedセクタ\n")
					end
					if (status & 0x200) != 0
						$stdout.print("  ステータス(#{id_c}/#{id_h}/#{id_s}/#{id_n}): 入れ子セクタ\n")
					end
					if (status | 0x31f) != 0x31f # 上記以外のビットが立っていたら
						$stdout.print("  ステータス(#{id_c}/#{id_h}/#{id_s}/#{id_n}): 不明な値(#{status.to_hex})\n")
					end
				end
			end
		end
	end

	def dump
		raise("Not implemented")
	end
end

# Virtual98(.fdd) ヘッダ+可変長データ https://www.pc98.org/project/doc/fdd.html
class V98FDD < DiskImage
	HEADER_SIZE = 0xc3fc

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[0, 7] == "VFD1.00"
	end

	def load(filedata)
		clear

		@mediatype = :"2hd" # 違ったらあとでリセット
		@comment = filedata[0x8, 0x80].force_encoding("WINDOWS-31J").encode.sub(/\0+$/, "")
		@writeprotect = (filedata[0x88, 2].to_word != 0) ? true : false
		special_read_drive = filedata[0x8a, 2].to_word

		cyls, heads = 80, 2
		offset = 0xdc
		(0 ... cyls * heads).each do |trkno|
			(0 ... 26).each do
				s = Sector.new
				s.c, s.h, s.r, s.n, fill_byte, s.ddam, s.mfm, hd, sector_offset =
					filedata[offset, 12].unpack("C4aC3V")
				offset += 12

				next  if s.c == 0xff

				if s.c > 90 || s.h > 1 || s.r > 32 || s.n > 6
					$stdout.print("  トラック#{trkno+1}のCHRN不正: #{s.c} #{s.h} #{s.r} #{s.n}\n")
					next  if s.n > 6 # 致命的なのでこのセクタはスキップ
				end

				case s.ddam
				when 0
					s.ddam = false
				when 1
					s.ddam = true
				else
					$stdout.print("  DDAMの値が不正: #{s.ddam}\n")
					s.ddam = nil
				end

				case s.mfm
				when 0
					s.mfm = false
				when 1
					s.mfm = true
				else
					$stdout.print("  MFの値が不正: #{s.mfm}\n")
					s.mfm = nil
				end

				if hd != 1
					$stdout.print("  2HDフラグが1でないセクタがあります: #{hd}\n")
					@mediatype = nil
				end

				ssize = 128 << s.n
				s.data = (sector_offset == 0xffffffff) ? fill_byte * ssize : filedata[sector_offset, ssize]

				trk = (@track[trkno] ||= Track.new)
				trk.sector << s
			end
		end

		if special_read_drive != 0xffff
			$stdout.print("  特殊読み込みドライブ設定があります: #{special_read_drive.to_hex}\n")

			next_point = special_read_drive # 0xc3dc
			begin
				trkno, in_ax, in_bx, in_cx, in_dx, out_ax, out_bx, out_cx, out_dx, out_flag, data_point, next_point, count, neg_count =
					filedata[next_point, 32].unpack("v10V2v2")
			end while(next_point != 0xffffffff && next_point != 0)
		end
	end

	def dump
		raise("Not implemented")
	end
end

# ERCVFD(.vfd) ヘッダ(64バイト)+セクタ毎に(ヘッダ(10バイト)+データ)
class ERCVFD < DiskImage
	HEADER_SIZE = 0x40

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[0, 8] == "ERCVFD01"
	end

	def load(filedata)
		raise("Not implemented")
	end

	def dump
		raise("Not implemented")
	end
end

# DIP(.dip) ヘッダ(256バイト)+べたデータ https://www.pc98.org/project/doc/dip.html
class DIP < DiskImage
	HEADER_SIZE = 256

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[0, 8] == "\x01\x08\x00\x13\x41\x00\x01\x00" &&
			filedata.length == HEADER_SIZE + (77 * 2 * 8 * 1024)
	end

	def load(filedata)
		clear

		@comment = filedata[0x10, 0xf0].force_encoding("WINDOWS-31J").encode.sub(/\0+$/, "")

		cyls, heads, nsecs, ssize = 77, 2, 8, 1024
		offset = HEADER_SIZE
		(0 ... cyls).each do |cyl|
			(0 ... heads).each do |head|
				trkno = cyl * heads + head
				trk = (@track[trkno] ||= Track.new)
				(1 .. nsecs).each do |sec|
					s = Sector.new
					s.c = cyl # シリンダは0オリジン
					s.h = head # ヘッドは0オリジン
					s.r = sec # レコードは1オリジン
					s.n = (ssize / 128).bit_length - 1
					s.data = filedata[offset, ssize] || ""
					offset += ssize
					trk.sector << s
				end
			end
		end

		excess_data_check(filedata.length, offset)
	end

	def dump
		raise("Not implemented")
	end
end

# D88(.d88) ディスクヘッダ+セクタ毎に(ヘッダ+データ) https://www.pc98.org/project/doc/d88.html https://github.com/waitingmoon/quasi88/blob/develop/document/FORMAT.TXT
class D88 < DiskImage
	HEADER_SIZE = 0x2a0 # or 0x2b0

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[0x10, 10] == "\0" * 10 &&
			[0x00, 0x10, 0x20, 0x21, 0x30, 0x40].include?(filedata[0x1b].to_byte) &&
			filedata.length == filedata[0x1c, 4].to_dword
	end

	def load(filedata)
		clear

		# Media flag
		media_flag = filedata[0x1b].to_byte
		case media_flag
		when 0x00 # 2D
			@mediatype = :"2d"
		when 0x10 # 2DD
			@mediatype = :"2dd"
		when 0x20 # 2HD
			@mediatype = :"2hd"
		when 0x21 # 2HD(1.44MB NP2kai)
			$stdout.print("  ヘッダのメディアタイプ: 2HD 1.44MB NP2kai拡張\n")
			@mediatype = :"2hd"
		when 0x30 # 1D
			@mediatype = :"1d"
		when 0x40 # 1DD
			@mediatype = :"1dd"
		else
			$stdout.print("  ヘッダのメディアタイプ不明: #{media_flag.to_hex}\n")
			@mediatype = :unknown
		end

		# Write protect flag
		@writeprotect = (filedata[0x1a].to_byte == 0) ? false : true

		# Disk name / comment
		@comment = filedata[0, 16].force_encoding("WINDOWS-31J").encode.sub(/\0+$/, "")

		# Track data
		track_offsets = filedata[0x20, 4 * 164].to_dwords
		header_size = track_offsets.find { |o| o != 0 }
		header_tracks = (header_size - 0x20) / 4 # 0x2b0(688byte:164entry) or 0x2a0(672byte:160entry)
		track_offsets = track_offsets.first(header_tracks)

		track_offsets.each.with_index do |offset, trkno|
			if offset == 0
				@track[trkno] = nil
			else
				trk = (@track[trkno] ||= Track.new)

				track_nsectors = nil
				begin
					s = Sector.new
					s.c, s.h, s.r, s.n, nsecs, s.mfm, s.ddam, s.status, rpm, datasize =
						filedata[offset, 16].unpack("C4vC3x4Cv")
					offset += 0x10

					if s.c > 90 || s.h > 1 || s.r > 32 || s.n > 6
						$stdout.print("  トラック#{trkno+1}のCHRN不正: #{s.c} #{s.h} #{s.r} #{s.n}\n")
						break  if s.n > 6 # 致命的なのでこのトラックはスキップ
					end

					if nsecs > 32
						$stdout.print("  トラック#{trkno+1}のセクタ数不正: #{nsecs}\n")
					end

					if !track_nsectors
						track_nsectors = nsecs
					elsif track_nsectors != nsecs
						$stdout.print("  トラック#{trkno+1}の総セクタ数が統一されていない: #{track_nsectors} != #{nsecs}\n")
					end

					case s.mfm
					when 0x00 # double density
						s.mfm = true
					when 0x40 # single density
						s.mfm = false
					else
						$stdout.print("  トラック#{trkno+1}のDensity flag不正: #{s.mfm.to_hex}\n")
						s.mfm = nil
					end

					case s.ddam
					when 0x00 # normal
						s.ddam = false
					when 0x10 #deleted
						s.ddam = true
					else
						$stdout.print("  トラック#{trkno+1}のDDAM flag不正: #{s.ddam.to_hex}\n")
						s.ddam = nil
					end

					if rpm == 0 || rpm == 1
						# OK:NOP
					else
						$stdout.print("  トラック#{trkno+1}のNP2kai RPM不正: #{rpm}\n")
					end

					ssize = 128 << s.n
					if ssize != datasize
						$stdout.print("  トラック#{trkno+1}のセクタのN値とデータサイズが異なる: N:#{ssize} != #{datasize}\n")
					end

					s.data = filedata[offset, ssize] || ""
					offset += ssize

					trk.sector << s
				end while trk.sector.length < nsecs

				next_track_start = (track_offsets[(trkno + 1) .. -1].find { |o| o != 0 }) || filedata.length
				if offset != next_track_start
					if offset < next_track_start
						$stdout.print("  トラック#{trkno+1}のデータの後に不要なデータがあります\n")
					else
						$stdout.print("  トラック#{trkno+1}のデータが次のトラックに達しています\n")
					end
				end
			end
		end
	end

	def dump
		raise("Not implemented")
	end
end

# Anex86(.fdi) ヘッダ(通常4096バイト)+べたデータ https://www.pc98.org/project/doc/hdi.html
class FDI < DiskImage
	HEADER_SIZE = 0x20 # コメント除く最小サイズ

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		return filedata[0, 4].to_dword == 0 &&
			[0x90, 0x30, 0x10].include?(filedata[4, 4].to_dword) &&
			filedata[0x8, 4].to_dword + filedata[0xc, 4].to_dword == filedata.length
	end

	def load(filedata)
		clear

		fddtype_id = filedata[4, 4].to_dword
		case fddtype_id
		when 0x90 # 2HD(1.2MB)
			@mediatype = :"2hd"
		when 0x30 # 2HD(1.44MB)
			@mediatype = :"2hd"
		when 0x10 # 2DD(640KB or 720KB)
			@mediatype = :"2dd"
		else
			$stdout.print("  メディアタイプ不明: #{fddtype_id.to_hex}\n")
			@mediatype = :unknown
		end

		headersize = filedata[0x8, 4].to_dword
		datasize = filedata[0xc, 4].to_dword
		ssize, nsecs, heads, cyls = filedata[0x10, 4 * 4].to_dwords
		$stdout.print("  ヘッダ情報: #{ssize}バイト × #{nsecs}セクタ × #{heads}ヘッド × #{cyls}トラック\n")

		@comment = filedata[0x20, headersize - 0x20].force_encoding("WINDOWS-31J").encode.sub(/\0+$/, "")

		calc_datasize = cyls * heads * nsecs * ssize
		if calc_datasize != datasize
			$stdout.print("  ヘッダ情報から算出したデータサイズとヘッダ情報のデータサイズが一致しません: #{calc_datasize} != #{datasize}\n")
		end

		if headersize + datasize != filedata.length
			$stdout.print("  ヘッダ情報のデータサイズと実際のファイルサイズが一致しません: #{headersize + datasize} != #{filedata.length}\n")
		end

		offset = headersize
		(0 ... cyls).each do |cyl|
			(0 ... heads).each do |head|
				trkno = cyl * heads + head
				trk = (@track[trkno] ||= Track.new)
				(1 .. nsecs).each do |sec|
					s = Sector.new
					s.c = cyl # シリンダは0オリジン
					s.h = head # ヘッドは0オリジン
					s.r = sec # レコードは1オリジン
					s.n = (ssize / 128).bit_length - 1
					s.data = filedata[offset, ssize] || ""
					offset += ssize
					trk.sector << s
				end
			end
		end

		excess_data_check(filedata.length, offset)
	end

	def dump
		raise("Not implemented")
	end
end

# DCP/DCU(.dcu) ヘッダ(162バイト)+べたデータ https://www.pc98.org/project/doc/dcp.html https://melog.info/archives/2004/09/30/94#comment-27
class DCU < DiskImage
	HEADER_SIZE = 1 + 160 + 1

	def self.image?(filedata)
		return false  if filedata.length < HEADER_SIZE

		track_map = filedata[1, 160].to_bytes
		track_map.each do |t|
			if t != 0 && t != 1
				return false
			end
		end

		media_type = filedata[0].to_byte
		case [media_type, filedata.length]
		when [0x01, HEADER_SIZE + (77 * 2 * 8 * 1024)] # 2HD(1.25MB 2HS)
			return true
		when [0x02, HEADER_SIZE + (80 * 2 * 15 * 512)] # 2HD(1.21MB 2HC)
			return true
		when [0x03, HEADER_SIZE + (80 * 2 * 18 * 512)] # 2HQ(1.44MB 2HDE)
			return true
		when [0x04, HEADER_SIZE + (80 * 2 * 8 * 512)] # 2DD(640KB)
			return true
		when [0x05, HEADER_SIZE + (80 * 2 * 9 * 512)] # 2DD(720KB)
			return true
		when [0x08, HEADER_SIZE + (80 * 2 * 9 * 1024)] # 2HD(1.44MB)
			return true
		when [0x11, HEADER_SIZE + (1*26*128 + 153*26*256)] # 2HD(Disk BASIC)
			return true
		when [0x19, HEADER_SIZE + (80 * 2 * 16 * 256)] # 2DD(Disk BASIC)
			return true
		when [0x21, HEADER_SIZE + (80 * 2 * 26 * 256)] # 2HD(26sector)
			return true
		end

		return false
	end

	def load(filedata)
		clear

		media_type = filedata[0].to_byte
		case media_type
		when 0x01 # 2HD(1.25MB 2HS)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 77, 2, 8, 1024
		when 0x02 # 2HD(1.21MB 2HC)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 80, 2, 15, 512
		when 0x03 # 2HQ(1.44MB 2HDE)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 80, 2, 18, 512
		when 0x04 # 2DD(640KB)
			@mediatype = :"2dd"
			cyls, heads, nsecs, ssize = 80, 2, 8, 512
		when 0x05 # 2DD(720KB)
			@mediatype = :"2dd"
			cyls, heads, nsecs, ssize = 80, 2, 9, 512
		when 0x08 # 2HD(1.44MB)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 80, 2, 9, 1024
		when 0x11 # 2HD(Disk BASIC)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize, ssize1 = 77, 2, 26, 256, 128
		when 0x19 # 2DD(Disk BASIC)
			@mediatype = :"2dd"
			cyls, heads, nsecs, ssize = 80, 2, 16, 256
		when 0x21 # 2HD(26sector)
			@mediatype = :"2hd"
			cyls, heads, nsecs, ssize = 80, 2, 26, 256
		else
			$stdout.print("  メディアタイプ不明: #{media_type.to_hex}\n")
			@mediatype = :unknown
			cyls, heads, nsecs, ssize = 0, 0, 0, 0
		end

		# トラック保存状態
		xtrack_map = filedata[1, 160].to_bytes
		xtrack_map.each.with_index do |flag, trkno|
			if flag == 0 || flag == 1
				# OK:NOP
			else
				$stdout.print("  #{trkno+1}トラックのデータ有無フラグが不正: #{flag}\n")
			end
		end

		# 全トラック格納フラグ
		all_cylinders_stored = filedata[0xa1].to_byte
		case all_cylinders_stored
		when 0
			# OK:NOP
		when 1
			$stdout.print("  全トラック格納フラグ: ON\n")
			(0 ... cyls * heads).each do |trkno|
				xtrack_map[trkno] = 1
			end
		else
			$stdout.print("  全トラック格納フラグ不正: #{all_cylinders_stored}\n")
		end

		# データ本体
		offset = HEADER_SIZE
		xtrack_map.each.with_index do |flag, trkno|
			case flag
			when 0 # なし
				@track[trkno] = nil
			when 1 # あり
				cyl = trkno / heads
				head = trkno % heads

				trk = (@track[trkno] ||= Track.new)
				(1 .. nsecs).each do |sec|
					s = Sector.new
					s.c = cyl # シリンダは0オリジン
					s.h = head # ヘッドは0オリジン
					s.r = sec # レコードは1オリジン
					s.n = (ssize / 128).bit_length - 1
					s.data = filedata[offset, ssize] || ""
					offset += ssize
					trk.sector << s
				end
			end
		end

		excess_data_check(filedata.length, offset)
	end

	def dump
		raise("Not implemented")
	end
end

# XDF(.xdf) べたデータ
class XDF < DiskImage
	HEADER_SIZE = 0
	Geometries = [
		# length   media  cyls heads  nsec ssize ssize1
		[1474560, :"2hd",   80,    2,   18,  512],			# 1.44MB 2HD
		[1474560, :"2hd",   80,    2,    9, 1024],			# 1.44MB 2HD
		[1261568, :"2hd",   77,    2,    8, 1024],			# 1.23MB 2HD
		[1228800, :"2hd",   80,    2,   15,  512],			# 1.2MB 2HD
		[1064960, :"2hd",   80,    2,   26,  256],			# 1.04MB 2HD
		[1021696, :"2hd",   77,    2,   26,  256,  128],	# DISK BASIC 2HD
		[ 819200, :"2dd",   80,    2,   10,  512],			# 800KB 2DD
		[ 737280, :"2dd",   80,    2,    9,  512],			# 720KB 2DD
		[ 655360, :"2dd",   80,    2,    8,  512],			# 640KB 2DD
		[ 655360, :"2dd",   80,    2,   16,  256],			# DISK BASIC 2DD
		[ 327680, :"2d",    40,    2,    8,  512],			# 320KB 2D
		[ 327680, :"1dd",   80,    1,    8,  512],			# 320KB 1DD
		[ 163840, :"1d",    40,    1,    8,  512],			# 160KB 1D
	]

	def self.image?(filedata)
		return Geometries.find{ |g| g[0] == filedata.length } ? true : false
	end

	def load(filedata)
		clear

		geom = Geometries.find{ |g| g[0] == filedata.length }
		cyls, heads, nsecs, ssize = geom[2 .. 5]

		offset = 0
		(0 ... cyls).each do |cyl|
			(0 ... heads).each do |head|
				trkno = cyl * heads + head
				trk = (@track[trkno] ||= Track.new)
				(1 .. nsecs).each do |sec|
					s = Sector.new
					s.c = cyl # シリンダは0オリジン
					s.h = head # ヘッドは0オリジン
					s.r = sec # レコードは1オリジン
					s.n = (ssize / 128).bit_length - 1
					s.data = filedata[offset, ssize] || ""
					offset += ssize
					trk.sector << s
				end
			end
		end

		excess_data_check(filedata.length, offset)
	end

	def dump
		raise("Not implemented")
	end
end

def fdimageid(filename)
	$stdout.print("#{filename}:\n")
	filedata = read_file(filename).freeze

	case
	# DIFC.X(.dim)
	when DIM.image?(filedata)
		$stdout.print("  💾 X68000 DIFC.X形式 [.dim]\n")
		image = DIM.new(data:filedata)
		image.report_all

	# T98Next R0(.nfd)
	when NFD_R0.image?(filedata)
		$stdout.print("  💾 T98-Next NFD r0形式 [.nfd]\n")
		image = NFD_R0.new(data:filedata)
		image.report_all

	# T98Next R1(.nfd)
	when NFD_R1.image?(filedata)
		$stdout.print("  💾 T98-Next NFD r1形式 [.nfd]\n")
		image = NFD_R1.new(data:filedata)
		image.report_all

	# SL9821(.slf)
	when SLF.image?(filedata)
		$stdout.print("  💾 SL9821形式 [.slf]\n")
		image = SLF.new(data:filedata)
		image.report_all

	# Virtual98(.fdd)
	when V98FDD.image?(filedata)
		$stdout.print("  💾 Virtual98形式 [.fdd]\n")
		image = V98FDD.new(data:filedata)
		image.report_all

	# ERCVFD(.vfd)
	when ERCVFD.image?(filedata)
		$stdout.print("  💾 ERCACHE ERCVFD形式 [.vfd]\n")
		# image = ERCVFD.new(data:filedata)
		# image.report_all

	# DIP(.dip)
	when DIP.image?(filedata)
		$stdout.print("  💾 DIP形式 [.dip]\n")
		image = DIP.new(data:filedata)
		image.report_all

	# D88(.d88)
	when D88.image?(filedata)
		$stdout.print("  💾 D88形式 [.d88 .d98 .88d .98d]\n")
		image = D88.new(data:filedata)
		image.report_all

	# Anex86(.fdi)
	when FDI.image?(filedata)
		$stdout.print("  💾 Anex86形式 [.fdi]\n")
		image = FDI.new(data:filedata)
		image.report_all

	# DCP/DCU(.dcu)
	when DCU.image?(filedata)
		$stdout.print("  💾 DCP/DCU形式 [.dcu .dcp]\n")
		image = DCU.new(data:filedata)
		image.report_all

	# XDF(.xdf)
	when XDF.image?(filedata)
		case filedata.length
		when 80 * 2 * 18 * 512 # 1.44MB 2HD
			$stdout.print("  💾 べたイメージ 2HD(1.44MB PC/AT) [.2hd]\n")
		when 77 * 2 * 8 * 1024 # 1.23MB 2HD
			$stdout.print("  💾 べたイメージ 2HD(1.23MB PC98) [.xdf .2hd .dup .hdm .tfd]\n")
		when 80 * 2 * 15 * 512 # 1.2MB 2HD
			$stdout.print("  💾 べたイメージ 2HD(1.2MB PC/AT) [.2hd]\n")
		when 80 * 2 * 9 * 512 # 720KB 2DD
			$stdout.print("  💾 べたイメージ 2DD(720KB MSX) [.dsk]\n")
		when 80 * 2 * 8 * 512 # 640KB 2DD
			$stdout.print("  💾 べたイメージ 2DD(640KB) [.2dd]\n")
		when 40 * 2 * 8 * 512 # 320KB 2D
			$stdout.print("  💾 べたイメージ 2D(320KB) [.2d]\n")
		when 40 * 1 * 8 * 512 # 160KB 1D
			$stdout.print("  💾 べたイメージ 1D(160KB) [.1d]\n")
		else
			$stdout.print("  💾 べたイメージ [.xdf]\n")
		end

		image = XDF.new(data:filedata)
		image.report_all

	else
		$stdout.print("  ❓ 形式不明(#{filedata.length}バイト)\n")
	end
end

# .dim → .xdf 変換
def strip_dim(filename)
	$stdout.print("#{filename}:\n")
	filedata = read_file(filename).freeze
	outfilename = filename + ".xdf"

	if !DIM.image?(filedata)
		$stderr.print("#{ProgName}: DIFC.X形式ではありません: #{filename}\n")
		return
	end

	case filedata.length
	when 256 + 77 * 2 * 8 * 1024 # 1261824
		data = filedata[256, 77 * 2 * 8 * 1024]

		$stdout.print("  → #{outfilename}:\n")
		write_file(outfilename, data)
	when 256 + 80 * 2 * 8 * 1024 # 1310976
		data = filedata[256, 77 * 2 * 8 * 1024]
		data2 = filedata[256 + 77 * 2 * 8 * 1024, (80 - 77) * 2 * 8 * 1024]
		if data2 != data2[0] * data2.length
			$stderr.print("#{ProgName}: オーバートラックデータがあります: #{filename}\n")
			return
		end

		$stdout.print("  → #{outfilename}:\n")
		write_file(outfilename, data)
	when 256 + 85 * 2 * 8 * 1024 # 1392896
		data = filedata[256, 77 * 2 * 8 * 1024]
		data2 = filedata[256 + 77 * 2 * 8 * 1024, (85 - 77) * 2 * 8 * 1024]
		if data2 != data2[0] * data2.length
			$stderr.print("#{ProgName}: オーバートラックデータがあります: #{filename}\n")
			return
		end

		$stdout.print("  → #{outfilename}:\n")
		write_file(outfilename, data)
	else
		$stdout.print("  形式不明(#{filedata.length}バイト)\n")
	end
end

# 9セクタ2DD(720KB)のイメージの各トラックの9セクタ目を切り捨てて8セクタ2DD(640KB)のイメージにする
def truncate_9(filename)
	$stdout.print("#{filename}:\n")
	filedata = read_file(filename).freeze

	if filedata.length == 80 * 2 * 9 * 512
		outdata = ""
		(0 ... 80 * 2).each do |track|
			outdata += filedata[track * 9 * 512, 8 * 512]
		end

		outfilename = filename + ".xdf"
		$stdout.print("  → #{outfilename}:\n")
		write_file(outfilename, outdata)
	elsif D88.image?(filedata) && filedata[0x1b].to_byte == 0x10
		track_offsets = filedata[0x20, 4 * 164].to_dwords
		header_size = track_offsets.find { |o| o != 0 }
		header_tracks = (header_size - 0x20) / 4
		track_offsets = track_offsets.first(header_tracks)

		outdata = filedata[0, header_size]
		(0 ... header_tracks).each do |track|
			track_offset = track_offsets[track]
			if track_offset != 0
				outdata[0x20 + 4 * track, 4] = [outdata.length].pack("V")

				(0 ... 8).each do |r|
					data = filedata[track_offset + 0x210 * r, 0x210]
					fail if data[4, 2].to_word != 9
					data[4, 2] = [8].pack("v")
					outdata += data
				end
			end
		end

		outdata[0x1c, 4] = [outdata.length].pack("V") # Disk size

		outfilename = filename + ".d88"
		$stdout.print("  → #{outfilename}:\n")
		write_file(outfilename, outdata)
	else
		$stdout.print("  形式不明(#{filedata.length}バイト)\n")
	end
end

def main(args)
	action = :identify

	args.options do |opt|
		opt.banner = "#{ProgName} v#{Version} #{Copyright}\n" +
						"Usage: #{ProgName} [options] file..."

		opt.on("--strip-dim",
		".dim → .xdf 変換") do
			action = :strip_dim
		end

		opt.on("--truncate_9",
		"9セクタ目を切り捨て") do
			action = :truncate_9
		end

		opt.parse!
		print(opt.help)  if args.empty?
	end

	args.each do |an_arg|
		if !File.exist?(an_arg)
			$stderr.print("#{ProgName}: File not found: #{an_arg}\n")
			break
		end

		case action
		when :identify
			fdimageid(an_arg)
		when :strip_dim
			strip_dim(an_arg)
		when :truncate_9
			truncate_9(an_arg)
		end
	end

	return 0
end

exit main(ARGV)
